name: Build and Deploy

on:
  push:
    branches: [main]
  workflow_dispatch:

permissions:
  contents: write
  pages: write
  id-token: write

jobs:
  imported:
    uses: peruibeloko/shared/.github/workflows/vue.yml@main